import { INavbarData } from "./inavbar.interface";

export const navbarData: INavbarData[] = [
  {
    routeLink: 'dashboard',
    icon: 'assignment',
    label: 'General',
    idmenu: 0,
    estado: 0,
    crear: 0,
    editar: 0,
    eliminar: 0,
    ver: 0,
    principal: 0,
    orden: 0,
    muestra: 0,
    parentID: -1,            //Change for x.parentID,
    items: [
      {
        routeLink: 'pages/companies-list',
        icon: 'apartment',  
        label: 'Compañías',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/entities-list',
        icon: 'store',  
        label: 'Entidades',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/products-list',
        icon: 'local_mall',
        label: 'Productos',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/devices-list',
        icon: 'phone_iphone',
        label: 'Dispositivos',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/license-type-list',
        icon: 'style',
        label: 'Tipo Licencias',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/license-list',
        icon: 'credit_card',
        label: 'Licencias',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/payment-list',
        icon: 'local_atm',
        label: 'Pagos',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
      {
        routeLink: 'pages/cxc-list',
        icon: 'request_quote',
        label: 'CXC',
        idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
      },
    ]
  },
  {
  routeLink: 'dashboard',
  icon: 'admin_panel_settings',
  label: 'Administrar',
  idmenu: 0,
  estado: 0,
  crear: 0,
  editar: 0,
  eliminar: 0,
  ver: 0,
  principal: 0,
  orden: 0,
  muestra: 0,
  parentID: -1, 
  items: [
    {
      routeLink: 'security/user-list',
      icon: 'group',
      label: 'Usuarios',
      idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
    },
    {
      routeLink: 'security/role-list',
      icon: 'manage_accounts',
      label: 'Roles',
      idmenu: 0,
      estado: 0,
      crear: 0,
      editar: 0,
      eliminar: 0,
      ver: 0,
      principal: 0,
      orden: 0,
      muestra: 0,
      parentID: -1, 
    },
    {
      routeLink: 'security/menu-list',
      icon: 'menu',
      label: 'Menu',
      idmenu: 0,
        estado: 0,
        crear: 0,
        editar: 0,
        eliminar: 0,
        ver: 0,
        principal: 0,
        orden: 0,
        muestra: 0,
        parentID: -1, 
    },
  ]
}


]

